---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - graph.kubeweaver.dev
  resources:
  - dependencygraphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - graph.kubeweaver.dev
  resources:
  - dependencygraphs/finalizers
  verbs:
  - update
- apiGroups:
  - graph.kubeweaver.dev
  resources:
  - dependencygraphs/status
  verbs:
  - get
  - patch
  - update
