apiVersion: graph.kubeweaver.dev/v1alpha1
kind: DependencyGraph
metadata:
  labels:
    app.kubernetes.io/name: kubeweaver
    app.kubernetes.io/managed-by: kustomize
  name: dependencygraph-sample
spec:
  # TODO(user): Add fields here
